### ISSUE TITLE
mar letezo file/dir nev teszteles egysegesitese touch/mkdir/stb.

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-MoSzE-2019-DreamTheater#4]
namost pepitaban ugyanennek a logikanak meg kellene lennie pl az mkdir-ben is, nem? (de ott mas van). Ha pedig mar ket helyen meg kellene lennie....

_Originally posted by @hegyhati in https://github.com/Teaching-projects/SZE-MoSzE-2019-DreamTheater/pull/3_

**Comment by Comerick** [comment]
Felnyomtam a javított változatot, légyszives checkold le :)
